server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
  
spring:
  application:
    name: EventService

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: eventpro
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: false
      properties:
        hibernate:
          highlight_sql: true
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
          type:
            trace: true

  security:
    oauth2:
      client:
        registration:
          event-client:
            authorization-grant-type: client_credentials
            client-id: event-client
            client-secret: jS93Jr9RHwbNQwUZyCTZX5Uyl5N56hph
            provider: event-provider
            scope: openid
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token
        provider:
          event-provider:
            authorization-uri: https://keycloak:8080/auth/realms/master/protocol/openid-connect/auth
            token-uri: https://keycloak:8080/auth/realms/master/protocol/openid-connect/token
            user-info-uri: https://keycloak:8080/auth/realms/master/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/master/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: event-group

kafka:
  topic:
    participant:
      checkedin: participant.checked.in
    alert: system.alerts